---
- name: Pass variable from one play to the next in a playbook
  hosts: localhost
  gather_facts: false
  vars:
    my_play_var: "play var value"

  tasks:

    - name: Declare fact
      ansible.builtin.set_fact:
        my_fact: "fact value"

    - name: Debug variable
      ansible.builtin.debug:
        var: my_play_var

    - name: Debug fact
      ansible.builtin.debug:
        var: my_fact

- name: Next play uses same facts and variables
  hosts: all
  gather_facts: false

  tasks:

    - name: Debug variable
      ansible.builtin.debug:
        var: my_play_var

    - name: Debug fact
      ansible.builtin.debug:
        var: my_fact

    - name: Debug hostvars
      ansible.builtin.debug:
        var: hostvars['localhost']['my_fact']

