---
- name: Variable Precedence Test
  hosts: host1
  gather_facts: false

  tasks:

    - name: Debug myvar
      ansible.builtin.debug:
        var: myvar

- name: Variable Precedence Test with a role
  hosts: host1
  gather_facts: false

  roles:
    - myrole
