---
- name: Fill a report file with lineinfile (compare with a template!)
  hosts: myhosts
  gather_facts: true

  tasks:

    - name: Copy the report skeleton
      ansible.builtin.copy:
        src: report.txt
        dest: /tmp/report.txt
        mode: '0644'

    - name: Fill in the hostname
      ansible.builtin.lineinfile:
        path: /tmp/report.txt
        regexp: ^HOST
        line: HOST={{ ansible_facts['hostname'] }}

    - name: Fill in the memory
      ansible.builtin.lineinfile:
        path: /tmp/report.txt
        regexp: ^MEMORY
        line: MEMORY={{ ansible_facts['memtotal_mb'] }}

    - name: Fill in the BIOS version
      ansible.builtin.lineinfile:
        path: /tmp/report.txt
        regexp: ^BIOS
        line: BIOS={{ ansible_facts['bios_version'] }}

    - name: Fill in the disk size
      ansible.builtin.lineinfile:
        path: /tmp/report.txt
        regexp: ^SDA
        line: SDA_DISK_SIZE={{ ansible_facts['devices']['sda']['size'] if 'sda' in ansible_facts['devices'] else 'NONE' }}
