---
- name: Fetch CMDB configuration
  hosts: all
  become: true
  gather_facts: false
  vars:
    cmdb_repo: https://github.com/csurgay/cmdb.git
    cmdb_dest: /tmp/cmdb

  tasks:
    - name: Clone CMDB repository
      ansible.builtin.git:
        repo: "{{ cmdb_repo }}"
        dest: "{{ cmdb_dest }}"
        version: main
        force: true
      delegate_to: controlnode
      run_once: true

    - name: Load variables from cloned vars.yml
      ansible.builtin.include_vars:
        file: "{{ cmdb_dest }}/vars.yml"
        name: cmdb
      delegate_to: controlnode
      run_once: true

    - name: Debug CMDB data
      ansible.builtin.debug:
        var: cmdb.data
      delegate_to: controlnode
      run_once: true

    - name: Install and start webserver package
      ansible.builtin.include_tasks: "service.yml"
      with_items: "{{ cmdb.data }}"
      when: inventory_hostname != "controlnode"

    - name: Test all hosts webservers
      ansible.builtin.uri:
        url: http://{{ ansible_host }}
        status_code: 200
      when: inventory_hostname != "controlnode"

