---
- name: Check Multiple Services State with include_tasks
  hosts: all
  become: false
  gather_facts: false

  tasks:

    - name: Check services is-active
      ansible.builtin.shell: systemctl is-active {{ item }}
      register: results_state
      with_items:
        - sshd
        - nginx
        - firewalld
      ignore_errors: true
      no_log: true

    - name: Format and print result
      ansible.builtin.include_tasks: print.yml
      with_items: "{{ results_state.results }}"
      no_log: true

